.mode csv input
create table fish (value int);
.separator " " ","
.import input fish

CREATE TABLE fish_count (num int, days_to_birth int);
INSERT INTO fish_count SELECT COUNT(*), value FROM fish GROUP BY value;
DROP TABLE fish;

INSERT INTO fish_count VALUES (0, 0);
INSERT INTO fish_count VALUES (0, 1);
INSERT INTO fish_count VALUES (0, 2);
INSERT INTO fish_count VALUES (0, 3);
INSERT INTO fish_count VALUES (0, 4);
INSERT INTO fish_count VALUES (0, 5);
INSERT INTO fish_count VALUES (0, 6);
INSERT INTO fish_count VALUES (0, 7);
INSERT INTO fish_count VALUES (0, 8);
-- INSERT INTO fish_count VALUES (0, 9);

DELETE FROM fish_count WHERE num = 0 AND days_to_birth IN (SELECT days_to_birth FROM fish_count WHERE num > 0);

UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;
UPDATE fish_count SET num = num + (SELECT num FROM fish_count WHERE days_to_birth = 0) WHERE days_to_birth = 7;
UPDATE fish_count SET days_to_birth = CASE WHEN days_to_birth = 0 THEN 8 ELSE days_to_birth - 1 END;


SELECT SUM(num) FROM fish_count;
-- SELECT GROUP_CONCAT(value) FROM fish;
