.mode csv input
create table fish (value int);
.separator " " ","
.import input fish

INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;
INSERT INTO fish SELECT 9 FROM fish WHERE value = 0;
UPDATE fish SET value = CASE WHEN value = 0 THEN 6 ELSE value - 1 END;

SELECT COUNT(*) FROM fish;
-- .dump
-- SELECT GROUP_CONCAT(value) FROM fish;
